# Generated by Django 3.0.4 on 2020-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20200408_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100)),
                ('occupation_type_info', models.CharField(choices=[('professional', 'professional'), ('traditional', 'traditional')], default='professional', max_length=40)),
                ('activity_sector_info', models.CharField(choices=[('medicine', 'medicine'), ('diagnosis', 'diagnosis'), ('test', 'test'), ('treatment', 'treatment')], default='test', max_length=40)),
                ('specialization_area', models.CharField(choices=[('dematologist', 'dematologist'), ('neurologist', 'neurologist'), ('surgeon', 'surgeon'), ('paediatrician', 'paediatrician')], default='paediatrician', max_length=50)),
            ],
        ),
    ]
